version: "2"
services:
  spa:
    command: sh -c "yarn; npm start"
    image: blockchain_webapp
    volumes:
      - "./spa:/spa"
    environment:
      TERM: xterm-256color
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    container_name: blockchain_webapp

  rest:
    command: sh -c "yarn; npm start"
    image: blockchain_rest
    volumes:
      - "./rest:/rest"
    environment:
      TERM: xterm-256color
      DEBUG: "*"
      BLOCKCHAIN_NODE_IP: node1
      MQTT_BROKER_IP: broker
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    container_name: blockchain_rest
